// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProviderAssignmentStarter.Data;

#nullable disable

namespace ProviderAssignmentStarter.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ProviderAssignmentStarter.Models.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LicenseId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Licenses");

                    b.HasData(
                        new { LicenseId = 1,  ProviderId = 1,  LicenseNumber = "LIC-2023-0001", LicenseStatus = "Active",    ExpirationDate = new DateTime(2026, 1, 15, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 2,  ProviderId = 1,  LicenseNumber = "LIC-2023-0002", LicenseStatus = "Suspended", ExpirationDate = new DateTime(2025, 6, 30, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 3,  ProviderId = 2,  LicenseNumber = "LIC-2023-0010", LicenseStatus = "Expired",   ExpirationDate = new DateTime(2024, 3, 22, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 4,  ProviderId = 2,  LicenseNumber = "LIC-2023-0011", LicenseStatus = "Active",    ExpirationDate = new DateTime(2026, 3, 22, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 5,  ProviderId = 3,  LicenseNumber = "LIC-2023-0020", LicenseStatus = "Active",    ExpirationDate = new DateTime(2026, 6, 10, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 6,  ProviderId = 3,  LicenseNumber = "LIC-2021-0021", LicenseStatus = "Expired",   ExpirationDate = new DateTime(2023, 6, 10, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 7,  ProviderId = 4,  LicenseNumber = "LIC-2022-0030", LicenseStatus = "Expired",   ExpirationDate = new DateTime(2023, 11, 5, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 8,  ProviderId = 5,  LicenseNumber = "LIC-2024-0040", LicenseStatus = "Active",    ExpirationDate = new DateTime(2027, 2, 1, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 9,  ProviderId = 6,  LicenseNumber = "LIC-2022-0050", LicenseStatus = "Active",    ExpirationDate = new DateTime(2025, 12, 31, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 10, ProviderId = 7,  LicenseNumber = "LIC-2023-0060", LicenseStatus = "Expired",   ExpirationDate = new DateTime(2024, 9, 3, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 11, ProviderId = 8,  LicenseNumber = "LIC-2021-0070", LicenseStatus = "Expired",   ExpirationDate = new DateTime(2022, 5, 14, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 12, ProviderId = 9,  LicenseNumber = "LIC-2024-0080", LicenseStatus = "Active",    ExpirationDate = new DateTime(2027, 4, 7, 0, 0, 0, DateTimeKind.Utc) },
                        new { LicenseId = 13, ProviderId = 10, LicenseNumber = "LIC-2024-0090", LicenseStatus = "Active",    ExpirationDate = new DateTime(2027, 5, 20, 0, 0, 0, DateTimeKind.Utc) });
                });

            modelBuilder.Entity("ProviderAssignmentStarter.Models.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProviderId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ProviderName", "County")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0");

                    b.ToTable("Providers");


                    b.HasData(
                        new { ProviderId = 1,  ProviderName = "Fulton Family Care",        County = "Fulton",   Status = "Active",   CreatedDate = new DateTime(2023, 1, 15, 0, 0, 0, DateTimeKind.Utc),  IsDeleted = false },
                        new { ProviderId = 2,  ProviderName = "DeKalb Medical Group",      County = "DeKalb",   Status = "Active",   CreatedDate = new DateTime(2023, 3, 22, 0, 0, 0, DateTimeKind.Utc),  IsDeleted = false },
                        new { ProviderId = 3,  ProviderName = "Gwinnett Health Services",  County = "Gwinnett", Status = "Active",   CreatedDate = new DateTime(2023, 6, 10, 0, 0, 0, DateTimeKind.Utc),  IsDeleted = false },
                        new { ProviderId = 4,  ProviderName = "Cobb County Clinics",       County = "Cobb",     Status = "Inactive", CreatedDate = new DateTime(2022, 11, 5, 0, 0, 0, DateTimeKind.Utc),  IsDeleted = false },
                        new { ProviderId = 5,  ProviderName = "Clayton Care Partners",     County = "Clayton",  Status = "Pending",  CreatedDate = new DateTime(2024, 2, 1, 0, 0, 0, DateTimeKind.Utc),   IsDeleted = false },
                        new { ProviderId = 6,  ProviderName = "Cherokee Wellness Center",  County = "Cherokee", Status = "Active",   CreatedDate = new DateTime(2022, 8, 19, 0, 0, 0, DateTimeKind.Utc),  IsDeleted = false },
                        new { ProviderId = 7,  ProviderName = "Henry County Health",       County = "Henry",    Status = "Active",   CreatedDate = new DateTime(2023, 9, 3, 0, 0, 0, DateTimeKind.Utc),   IsDeleted = false },
                        new { ProviderId = 8,  ProviderName = "Archived Provider Inc",     County = "Fulton",   Status = "Inactive", CreatedDate = new DateTime(2021, 5, 14, 0, 0, 0, DateTimeKind.Utc), IsDeleted = true,  DeletedAt = new DateTime(2024, 1, 10, 0, 0, 0, DateTimeKind.Utc) },
                        new { ProviderId = 9,  ProviderName = "Douglas Diagnostic Center", County = "Douglas",  Status = "Active",   CreatedDate = new DateTime(2024, 4, 7, 0, 0, 0, DateTimeKind.Utc),   IsDeleted = false },
                        new { ProviderId = 10, ProviderName = "Forsyth Primary Care",      County = "Forsyth",  Status = "Pending",  CreatedDate = new DateTime(2024, 5, 20, 0, 0, 0, DateTimeKind.Utc),  IsDeleted = false });
                });

            modelBuilder.Entity("ProviderAssignmentStarter.Models.License", b =>
                {
                    b.HasOne("ProviderAssignmentStarter.Models.Provider", "Provider")
                        .WithMany("Licenses")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ProviderAssignmentStarter.Models.Provider", b =>
                {
                    b.Navigation("Licenses");
                });
#pragma warning restore 612, 618
        }
    }
}
